export default {
  nav: { dashboard: 'لوحة التحكم', animals: 'حيواناتي', consultations: 'الاستشارات', marketplace: 'المتجر', notifications: 'الإشعارات', settings: 'الإعدادات', logout: 'تسجيل الخروج', forum: 'المنتدى', iot: 'أجهزة الاستشعار', ai_diagnostic: 'تشخيص الذكاء الاصطناعي' },
  auth: { login: 'تسجيل الدخول', register: 'إنشاء حساب', phone: 'رقم الهاتف', email: 'البريد الإلكتروني', password: 'كلمة المرور', name: 'الاسم الكامل', send_otp: 'استقبال رمز SMS', verify_otp: 'تحقق من الرمز', otp_placeholder: 'رمز مكون من 6 أرقام', login_sms: 'تسجيل الدخول عبر SMS', login_email: 'تسجيل الدخول عبر البريد', farmer: 'مربي', veterinarian: 'طبيب بيطري', vendor: 'مورد' },
  dashboard: { title: 'لوحة التحكم', welcome: 'مرحباً', animals: 'الحيوانات', consultations: 'الاستشارات', alerts: 'التنبيهات', orders: 'الطلبات', add_animal: 'إضافة حيوان', request_consultation: 'طلب استشارة', view_all: 'عرض الكل', healthy: 'بصحة جيدة', sick: 'مريض', treatment: 'علاج' },
  animals: { title: 'إدارة القطيع', add: 'إضافة حيوان', name: 'الاسم', type: 'النوع', breed: 'السلالة', age: 'العمر', weight: 'الوزن (كغ)', status: 'الحالة الصحية', photo: 'صورة', vaccinations: 'التطعيمات', health_history: 'السجل الصحي', cattle: 'أبقار', sheep: 'أغنام', goat: 'ماعز', poultry: 'دواجن', horse: 'خيول', pig: 'خنازير', camel: 'جمال' },
  consultation: { title: 'استشارة بيطرية', new: 'استشارة جديدة', subject: 'سبب الاستشارة', symptoms: 'الأعراض الملاحظة', send: 'إرسال', type_message: 'اكتب رسالتك...', accept: 'قبول', refuse: 'رفض', close: 'إغلاق', prescription: 'وصفة طبية', urgent: 'عاجل', normal: 'عادي', pending: 'في الانتظار', active: 'جارية', closed: 'مغلقة' },
  marketplace: { title: 'متجر بيطري', search: 'البحث عن منتج', add_to_cart: 'أضف إلى السلة', order: 'اطلب', pay: 'ادفع', payment_method: 'طريقة الدفع', orange_money: 'أورانج موني', mtn_momo: 'MTN موبايل موني', moov_money: 'موف موني', delivery: 'توصيل', pickup: 'استلام', stock: 'المخزون المتاح', category: { vaccine: 'لقاحات', medicine: 'أدوية', antiparasitic: 'مضادات طفيلية', nutrition: 'تغذية', equipment: 'معدات' } },
  tebe: { title: 'تشخيص Tebe بالذكاء الاصطناعي', subtitle: 'تحليل بصري مدعوم بالذكاء الاصطناعي', upload_photo: 'التقاط أو اختيار صورة', upload_video: 'تسجيل فيديو', analyze: 'تحليل', analyzing: 'جاري التحليل...', result: 'نتيجة التشخيص', confidence: 'الموثوقية', severity: { none: 'طبيعي', low: 'خفيف', medium: 'متوسط', high: 'خطير', critical: 'حرج' }, consult_vet: 'استشر طبيباً بيطرياً', auto_care: 'يمكن العلاج الذاتي', disclaimer: 'هذا التشخيص استرشادي. استشر طبيباً بيطرياً للتأكيد.' },
  iot: { title: 'أجهزة الاستشعار والأطواق', devices: 'الأجهزة', online: 'متصل', offline: 'غير متصل', battery: 'البطارية', temperature: 'الحرارة', activity: 'النشاط', alerts: 'تنبيهات الأجهزة', normal: 'طبيعي', alert: 'تنبيه', register_device: 'تسجيل جهاز' },
  offline: { offline: 'غير متصل', syncing: 'جاري المزامنة...', synced: 'تمت المزامنة', pending_actions: 'إجراءات معلقة: {{count}}' },
  common: { save: 'حفظ', cancel: 'إلغاء', confirm: 'تأكيد', delete: 'حذف', edit: 'تعديل', loading: 'جار التحميل...', error: 'خطأ', success: 'نجاح', close: 'إغلاق', back: 'رجوع', next: 'التالي', yes: 'نعم', no: 'لا', search: 'بحث', filter: 'تصفية', date: 'التاريخ', actions: 'الإجراءات', details: 'التفاصيل', required: 'مطلوب' }
};
