export default {
  nav: { dashboard: 'Dashboard', animals: 'My Animals', consultations: 'Consultations', marketplace: 'Shop', notifications: 'Notifications', settings: 'Settings', logout: 'Logout', forum: 'Forum', iot: 'IoT Sensors', ai_diagnostic: 'AI Diagnostic' },
  auth: { login: 'Login', register: 'Register', phone: 'Phone number', email: 'Email', password: 'Password', name: 'Full name', send_otp: 'Receive SMS code', verify_otp: 'Verify code', otp_placeholder: '6-digit code', login_sms: 'Login via SMS', login_email: 'Login via email', farmer: 'Farmer', veterinarian: 'Veterinarian', vendor: 'Vendor' },
  dashboard: { title: 'Dashboard', welcome: 'Welcome', animals: 'Animals', consultations: 'Consultations', alerts: 'Alerts', orders: 'Orders', add_animal: 'Add animal', request_consultation: 'Request consultation', view_all: 'View all', healthy: 'Healthy', sick: 'Sick', treatment: 'Treatment' },
  animals: { title: 'Herd Management', add: 'Add animal', name: 'Name', type: 'Species', breed: 'Breed', age: 'Age', weight: 'Weight (kg)', status: 'Health status', photo: 'Photo', vaccinations: 'Vaccinations', health_history: 'Health history', cattle: 'Cattle', sheep: 'Sheep', goat: 'Goat', poultry: 'Poultry', horse: 'Horse', pig: 'Pig', camel: 'Camel' },
  consultation: { title: 'Veterinary consultation', new: 'New consultation', subject: 'Reason', symptoms: 'Observed symptoms', send: 'Send', type_message: 'Type your message...', accept: 'Accept', refuse: 'Refuse', close: 'Close', prescription: 'Prescription', urgent: 'URGENT', normal: 'Normal', pending: 'Pending', active: 'Active', closed: 'Closed' },
  marketplace: { title: 'Veterinary shop', search: 'Search product', add_to_cart: 'Add to cart', order: 'Order', pay: 'Pay', payment_method: 'Payment method', orange_money: 'Orange Money', mtn_momo: 'MTN MoMo', moov_money: 'Moov Money', delivery: 'Delivery', pickup: 'Pickup', stock: 'Available stock', category: { vaccine: 'Vaccines', medicine: 'Medicines', antiparasitic: 'Antiparasitics', nutrition: 'Nutrition', equipment: 'Equipment' } },
  tebe: { title: 'Tebe AI Diagnostic', subtitle: 'Visual analysis powered by artificial intelligence', upload_photo: 'Take or choose a photo', upload_video: 'Record a video', analyze: 'Analyze', analyzing: 'Analyzing...', result: 'Diagnostic result', confidence: 'Confidence', severity: { none: 'Normal', low: 'Mild', medium: 'Moderate', high: 'Serious', critical: 'CRITICAL' }, consult_vet: 'Consult a vet', auto_care: 'Self-care possible', disclaimer: 'This diagnosis is indicative. Consult a vet for confirmation.' },
  iot: { title: 'IoT Sensors & Collars', devices: 'Devices', online: 'Online', offline: 'Offline', battery: 'Battery', temperature: 'Temperature', activity: 'Activity', alerts: 'Sensor alerts', normal: 'Normal', alert: 'Alert', register_device: 'Register device' },
  offline: { offline: 'Offline', syncing: 'Syncing...', synced: 'Synced', pending_actions: 'Pending actions: {{count}}' },
  common: { save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete', edit: 'Edit', loading: 'Loading...', error: 'Error', success: 'Success', close: 'Close', back: 'Back', next: 'Next', yes: 'Yes', no: 'No', search: 'Search', filter: 'Filter', date: 'Date', actions: 'Actions', details: 'Details', required: 'Required' }
};
