// Haoussa (Hausa) translations — Nigeria, Niger, Cameroun Nord
export default {
  nav: { dashboard: 'Allon aiki', animals: 'Dabbobin na', consultations: 'Shawarwari', marketplace: 'Kasuwa', notifications: 'Sanarwa', settings: 'Saituna', logout: 'Fita', forum: 'Tattaunawa', iot: 'na\'urori IoT', ai_diagnostic: 'Ganewar Tebe' },
  auth: { login: 'Shiga', register: 'Yi rajista', phone: 'Lambar waya', email: 'Imel', password: 'Kalmar sirri', name: 'Suna', send_otp: 'Karɓi lamba ta SMS', verify_otp: 'Tabbatar da lamba', otp_placeholder: 'Lamba ɗin 6', login_sms: 'Shiga ta SMS', login_email: 'Shiga ta imel', farmer: 'Manomi', veterinarian: 'Likitan dabbobi', vendor: 'Dan kasuwa' },
  dashboard: { title: 'Allon aiki', welcome: 'Barka da zuwa', animals: 'Dabbobi', consultations: 'Shawarwari', alerts: 'Gargaɗi', orders: 'Oda', add_animal: 'Ƙara dabba', request_consultation: 'Nemi shawarar likita', view_all: 'Duba duka', healthy: 'Lafiyayye', sick: 'Mai rashin lafiya', treatment: 'Magani' },
  animals: { title: 'Kula da dabbobi', add: 'Ƙara dabba', name: 'Suna', type: 'Nau\'in', breed: 'Kabilar', age: 'Shekaru', weight: 'Nauyi (kg)', status: 'Lafiya', photo: 'Hoto', vaccinations: 'Allurar rigakafi', health_history: 'Tarihin lafiya', cattle: 'Shanu', sheep: 'Tumaki', goat: 'Awaki', poultry: 'Kaji', horse: 'Doki', pig: 'Aladu', camel: 'Rakumi' },
  consultation: { title: 'Ganin likitan dabbobi', new: 'Sabuwar shawarar', subject: 'Dalilin zuwa', symptoms: 'Alamu na rashin lafiya', send: 'Aika', type_message: 'Rubuta saƙo...', accept: 'Karɓa', refuse: 'Ƙi', close: 'Kare', prescription: 'Takardar magani', urgent: 'GAGGAWA', normal: 'Na al\'ada', pending: 'Ana jira', active: 'Ana tafiya', closed: 'An kare' },
  marketplace: { title: 'Kasuwar dabbobi', search: 'Nemi kaya', add_to_cart: 'Ƙara wa kwando', order: 'Yi oda', pay: 'Biya', payment_method: 'Hanyar biyan kuɗi', orange_money: 'Orange Money', mtn_momo: 'MTN MoMo', moov_money: 'Moov Money', delivery: 'Isar da kaya', pickup: 'Ɗauka kai tsaye', stock: 'Adadin kaya', category: { vaccine: 'Allurar rigakafi', medicine: 'Magunguna', antiparasitic: 'Magani ɗibbu', nutrition: 'Abinci', equipment: 'Kayan aiki' } },
  tebe: { title: 'Ganewar Tebe IA', subtitle: 'Dubawa ta hoto/bidiyo', upload_photo: 'Ɗauki hoto', upload_video: 'Yi bidiyo', analyze: 'Gano', analyzing: 'Ana ganowa...', result: 'Sakamakon ganewar', confidence: 'Amintattu', severity: { none: 'Lafiyayye', low: 'Ƙarami', medium: 'Matsakaici', high: 'Mai tsanani', critical: 'GAGGAWA' }, consult_vet: 'Je ga likitan dabbobi', auto_care: 'Kula da kansa', disclaimer: 'Wannan shine shawara kawai. Likita zai tabbatar.' },
  iot: { title: 'na\'urori & Kwalba IoT', devices: 'Na\'urori', online: 'Aiki', offline: 'Kashe', battery: 'Batir', temperature: 'Zafi', activity: 'Aiki', alerts: 'Gargaɗin na\'ura', normal: 'Na al\'ada', alert: 'Gargaɗi', register_device: 'Yi rajista na\'ura' },
  offline: { offline: 'Ba cibiyar sadarwa', syncing: 'Ana aika...', synced: 'An aika', pending_actions: 'Ayyuka da ke jira: {{count}}' },
  common: { save: 'Ajiye', cancel: 'Soke', confirm: 'Tabbatar', delete: 'Share', edit: 'Gyara', loading: 'Ana lodawa...', error: 'Kuskure', success: 'An yi nasara', close: 'Rufe', back: 'Koma baya', next: 'Gaba', yes: 'Ee', no: 'A\'a', search: 'Bincika', filter: 'Tace', date: 'Kwanan', actions: 'Ayyuka', details: 'Cikakken bayani', required: 'Tilas' }
};
