// Wolof translations — Sénégal, Gambie, Mauritanie
export default {
  nav: { dashboard: 'Tabl bu jëf', animals: 'Sàppam yi', consultations: 'Xam-xam', marketplace: 'Màrse', notifications: 'Xibaar', settings: 'Sett', logout: 'Dem', forum: 'Diisoo', iot: 'IoT yi', ai_diagnostic: 'Diagnos Tebe' },
  auth: { login: 'Dugg', register: 'Bind sa tur', phone: 'Nimero telefon', email: 'Imel', password: 'Kode bu sëkk', name: 'Sa tur', send_otp: 'Yónnee kode SMS', verify_otp: 'Wér kode', otp_placeholder: 'Kode 6 aji', login_sms: 'Dugg ak SMS', login_email: 'Dugg ak imel', farmer: 'Serigñe dëkk', veterinarian: 'Doktëër yu wéex', vendor: 'Bizniskat' },
  dashboard: { title: 'Tabl bu jëf', welcome: 'Dalal ak jàmm', animals: 'Sàppam', consultations: 'Xam-xam', alerts: 'Jàng', orders: 'Commande', add_animal: 'Yokk sàpp', request_consultation: 'Laaj doktëër', view_all: 'Xool yépp', healthy: 'Bu baax', sick: 'Bu nexor', treatment: 'Dafa wonn' },
  animals: { title: 'Dëkkénte sàppam', add: 'Yokk sàpp bu bees', name: 'Tur', type: 'Xèp', breed: 'Wàllu', age: 'At', weight: 'Néeg (kg)', status: 'Wér', photo: 'Xéex', vaccinations: 'Pikir', health_history: 'Dàq bu wér', cattle: 'Nag yi', sheep: 'Xar yi', goat: 'Bëy yi', poultry: 'Gànnaar yi', horse: 'Fas yi', pig: 'Mbëx yi', camel: 'Yaxaneer yi' },
  consultation: { title: 'Xam-xam ak doktëër', new: 'Xam-xam bu bees', subject: 'Doxo', symptoms: 'Xam ci ab nexor', send: 'Yónnee', type_message: 'Bind sa xibaar...', accept: 'Jaamu', refuse: 'Bañ', close: 'Tëj', prescription: 'Ordonnance', urgent: 'GAAW', normal: 'Bu lekk', pending: 'Xarit', active: 'Di dox', closed: 'Jeex' },
  marketplace: { title: 'Màrse yu wéex', search: 'Saaru', add_to_cart: 'Yokk ci panier', order: 'Commande', pay: 'Fay', payment_method: 'Yoon bu fay', orange_money: 'Orange Money', mtn_momo: 'MTN MoMo', moov_money: 'Moov Money', delivery: 'Joxe', pickup: 'Jël', stock: 'Stock', category: { vaccine: 'Pikir yi', medicine: 'Garab yi', antiparasitic: 'Anti-parasit', nutrition: 'Lëkkël', equipment: 'Jumtukaay' } },
  tebe: { title: 'Diagnos Tebe IA', subtitle: 'Xool ak xéex/vide', upload_photo: 'Jël xéex', upload_video: 'Jël vide', analyze: 'Xam', analyzing: 'Xamal ci...', result: 'Reepaar', confidence: 'Sàkku', severity: { none: 'Bu baax', low: 'Bu ndaw', medium: 'Dëkk', high: 'Bu dëgël', critical: 'GAAW' }, consult_vet: 'Dem doktëër yu wéex', auto_care: 'Mbottu sa bopp', disclaimer: 'Xam-xamm bii indikaatif la. Doktëër bu wér yi wér.' },
  iot: { title: 'Jumtukaay & IoT', devices: 'Jumtukaay', online: 'Di liggéey', offline: 'Mënul', battery: 'Batëri', temperature: 'Weex', activity: 'Liggéey', alerts: 'Jàng jumtukaay', normal: 'Bu lekk', alert: 'Jàng', register_device: 'Bind jumtukaay' },
  offline: { offline: 'Mënul internet', syncing: 'Di sync...', synced: 'Sync jeex', pending_actions: 'Liggéey yi xarit: {{count}}' },
  common: { save: 'Bàkk', cancel: 'Bañ', confirm: 'Sàkku', delete: 'Fàll', edit: 'Soppi', loading: 'Di yóbbu...', error: 'Jëfandikukaay', success: 'Baax na', close: 'Tëj', back: 'Dellu', next: 'Kanam', yes: 'Waaw', no: 'Déedéet', search: 'Saaru', filter: 'Tëral', date: 'Bés', actions: 'Liggéey', details: 'Kanam kanam', required: 'Waajib' }
};
